###################################################
# +---------------------------------------------+ #
# |             Database Connection             | #
# +---------------------------------------------+ #
###################################################

# CAUTION! Developer mode will drop all database tables on startup. DO NOT USE IN PRODUCTION.
developer-mode: true

# Database connection settings.
mysql:
  host: localhost
  port: 3306
  username: unitedeconomy
  password: unitedeconomy
  database: unitedeconomy

use-per-world-accounts: false

default-world-name: default
default-currency:


currencies:
  Gold:
    symbol: 'G'
    format: '%,.2fG'
    singular: 'Gold'
    plural: 'Gold'
  Dollars:
    symbol: '$'
    format: '$%,.2f'
    singular: 'Dollar'
    plural: 'Dollars'
